import Play from "./play.svg?react"
import VolumeLow from "./volume-low.svg?react"
import VolumeHigh from "./volume-high.svg?react"
import Search from "./search.svg?react"
import Minimize from "./minimize.svg?react"
import Unminimize from "./unminimize.svg?react"
import Clip from "./clip.svg?react"
import Logo from "ui/icons/eye.svg?react"
import Pause from "./pause.svg?react"
import Arrow from "./arrow-up.svg?react"
import DocumentTxt from "./document-txt.svg?react"
import Github from "./github.svg?react"
import Menu from "./menu.svg?react"
import Close from "./close.svg?react"

export { Play, VolumeHigh, VolumeLow, Search, Minimize, Unminimize, Clip, Logo, Pause, Arrow, DocumentTxt, Github, Menu, Close }
